<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>iconOrange.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="View\firin.png" />
    <None Remove="View\images\1.gif" />
    <None Remove="View\images\2.gif" />
    <None Remove="View\images\3.gif" />
    <None Remove="View\images\AddBtn.png" />
    <None Remove="View\images\background.png" />
    <None Remove="View\images\background2.png" />
    <None Remove="View\images\DelBtn.png" />
    <None Remove="View\images\firin.png" />
    <None Remove="View\images\FolderBtn.png" />
    <None Remove="View\images\Logo.png" />
    <None Remove="View\images\sagacikassa.png" />
    <None Remove="View\images\sagacikyukari.png" />
    <None Remove="View\images\sagkapaliassa.png" />
    <None Remove="View\images\sagkapaliyukari.png" />
    <None Remove="View\images\SaveBtn.png" />
    <None Remove="View\images\SermakLogo.png" />
    <None Remove="View\images\SettingBtn.png" />
    <None Remove="View\images\solacikassa.png" />
    <None Remove="View\images\solacikyukari.png" />
    <None Remove="View\images\solkapaliassa.png" />
    <None Remove="View\images\solkapaliyukari.png" />
    <None Remove="View\klepeMerkez.png" />
    <None Remove="View\sagKlepe.png" />
    <None Remove="View\solKlepe.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="iconOrange.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="View\firin.png" />
    <Resource Include="View\images\sagacikassa.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Sharp7" Version="1.1.84" />
    <PackageReference Include="XamlAnimatedGif" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="View\images\3.gif" />
    <Resource Include="View\images\AddBtn.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\images\background.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\images\background2.png" />
    <Resource Include="View\images\DelBtn.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\images\firin.png" />
    <Resource Include="View\images\FolderBtn.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\images\Logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\images\sagacikyukari.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\images\sagkapaliassa.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\images\sagkapaliyukari.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\images\SaveBtn.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\images\SermakLogo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\images\SettingBtn.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\images\solacikassa.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\images\solacikyukari.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\images\solkapaliassa.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\images\solkapaliyukari.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\klepeMerkez.png" />
    <Resource Include="View\sagKlepe.png" />
    <Resource Include="View\solKlepe.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
