//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmerikaKamaraFirin {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmerikaKamaraFirin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string adim {
            get {
                return ResourceManager.GetString("adim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Steps   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string adimlar {
            get {
                return ResourceManager.GetString("adimlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Address range exceeded. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string adres_araligi_disina_cikildi {
            get {
                return ResourceManager.GetString("adres_araligi_disina_cikildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarms benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AktifAlarm {
            get {
                return ResourceManager.GetString("AktifAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarms   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string alarmlar {
            get {
                return ResourceManager.GetString("alarmlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarms   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string alarms {
            get {
                return ResourceManager.GetString("alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid received data size. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string alinan_veri_boyutu_gecersiz {
            get {
                return ResourceManager.GetString("alinan_veri_boyutu_gecersiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Homepage   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interface is loading... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string arayuz_yukleniyor {
            get {
                return ResourceManager.GetString("arayuz_yukleniyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the recipe? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_the_recipe {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_the_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No password to set or clear. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ayarlanacak_veya_temizlenecek_sifre_yok {
            get {
                return ResourceManager.GetString("ayarlanacak_veya_temizlenecek_sifre_yok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ayarlar {
            get {
                return ResourceManager.GetString("ayarlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flue Damper Opening (%) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string baca_aciklik {
            get {
                return ResourceManager.GetString("baca_aciklik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnecting... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string baglanti_kapatiliyor {
            get {
                return ResourceManager.GetString("baglanti_kapatiliyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success, operation completed smoothly. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string basarili_islem_sorunsuz_tamamlandi {
            get {
                return ResourceManager.GetString("basarili_islem_sorunsuz_tamamlandi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string bilgilendirme {
            get {
                return ResourceManager.GetString("bilgilendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string bir_hatayla_karsilasildi {
            get {
                return ResourceManager.GetString("bir_hatayla_karsilasildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buffer On benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string buffer_acik {
            get {
                return ResourceManager.GetString("buffer_acik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buffer Status Info   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string buffer_durum_bilgisi {
            get {
                return ResourceManager.GetString("buffer_durum_bilgisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buffer Off benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string buffer_kapali {
            get {
                return ResourceManager.GetString("buffer_kapali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string calisiyor {
            get {
                return ResourceManager.GetString("calisiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Too many items sent. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cok_fazla_oge_gonderildi {
            get {
                return ResourceManager.GetString("cok_fazla_oge_gonderildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Config benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Deletion benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string confirm_deletion {
            get {
                return ResourceManager.GetString("confirm_deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Otomasyon benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string data_otomasyon {
            get {
                return ResourceManager.GetString("data_otomasyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   min benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string dk {
            get {
                return ResourceManager.GetString("dk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopping benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string durduruldu {
            get {
                return ResourceManager.GetString("durduruldu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Furnace PLC connection failed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fırın_PLC_Baglanamadi {
            get {
                return ResourceManager.GetString("fırın_PLC_Baglanamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Function does not exist. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fonksiyon_mevcut_degil {
            get {
                return ResourceManager.GetString("fonksiyon_mevcut_degil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Function rejected. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fonksiyon_reddedildi {
            get {
                return ResourceManager.GetString("fonksiyon_reddedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Function not applied. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fonksiyon_uygulanmamis {
            get {
                return ResourceManager.GetString("fonksiyon_uygulanmamis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group 1  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string G1degeri {
            get {
                return ResourceManager.GetString("G1degeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group 2 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string G2Degeri {
            get {
                return ResourceManager.GetString("G2Degeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elapsed Time benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gecenZaman {
            get {
                return ResourceManager.GetString("gecenZaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid block size. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gecersiz_blok_boyutu {
            get {
                return ResourceManager.GetString("gecersiz_blok_boyutu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid block number. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gecersiz_blok_numarasi {
            get {
                return ResourceManager.GetString("gecersiz_blok_numarasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid block type. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gecersiz_blok_turu {
            get {
                return ResourceManager.GetString("gecersiz_blok_turu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid value. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gecersiz_deger {
            get {
                return ResourceManager.GetString("gecersiz_deger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid ISO PDU (Protocol Data Unit) detected. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gecersiz_iso_pdu_protokol_veri_birimi_algilandi {
            get {
                return ResourceManager.GetString("gecersiz_iso_pdu_protokol_veri_birimi_algilandi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid parameter number. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gecersiz_parametre_numarasi {
            get {
                return ResourceManager.GetString("gecersiz_parametre_numarasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid parameters sent. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gecersiz_parametreler_gonderildi {
            get {
                return ResourceManager.GetString("gecersiz_parametreler_gonderildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid password. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gecersiz_sifre {
            get {
                return ResourceManager.GetString("gecersiz_sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid transport size. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gecersiz_tasima_boyutu {
            get {
                return ResourceManager.GetString("gecersiz_tasima_boyutu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid data length. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gecersiz_veri_uzunlugu {
            get {
                return ResourceManager.GetString("gecersiz_veri_uzunlugu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Alarms benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GecmisAlarm {
            get {
                return ResourceManager.GetString("GecmisAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please log in! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string giris_yapiniz {
            get {
                return ResourceManager.GetString("giris_yapiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error content saved to log. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hata_icerigi_gunluge_kaydedildi {
            get {
                return ResourceManager.GetString("hata_icerigi_gunluge_kaydedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Page   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hata_sayfasi {
            get {
                return ResourceManager.GetString("hata_sayfasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Temperature  (C) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hedef_sicaklik {
            get {
                return ResourceManager.GetString("hedef_sicaklik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Content   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string icerik {
            get {
                return ResourceManager.GetString("icerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation timed out. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string islem_zaman_asimina_ugradi {
            get {
                return ResourceManager.GetString("islem_zaman_asimina_ugradi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ISO connection failed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string iso_baglantisi_basarisiz_oldu {
            get {
                return ResourceManager.GetString("iso_baglantisi_basarisiz_oldu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid ISO data size. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string iso_veri_boyutu_gecersiz {
            get {
                return ResourceManager.GetString("iso_veri_boyutu_gecersiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Requested item not found. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string istenen_oge_mevcut_degil {
            get {
                return ResourceManager.GetString("istenen_oge_mevcut_degil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chamber Oven   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kamara_firin {
            get {
                return ResourceManager.GetString("kamara_firin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kaydet {
            get {
                return ResourceManager.GetString("kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log File Not Found benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string logyok {
            get {
                return ResourceManager.GetString("logyok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Furnace Statu : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Machine_Statu {
            get {
                return ResourceManager.GetString("Machine_Statu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mainwindow   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mainwindow {
            get {
                return ResourceManager.GetString("mainwindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string manual {
            get {
                return ResourceManager.GetString("manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string manuel {
            get {
                return ResourceManager.GetString("manuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   m/min   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mdk {
            get {
                return ResourceManager.GetString("mdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MoveStoryboard benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string movestoryboard {
            get {
                return ResourceManager.GetString("movestoryboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Recipe   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string new_recipe {
            get {
                return ResourceManager.GetString("new_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Step benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string newadim {
            get {
                return ResourceManager.GetString("newadim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous operation is still pending. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string onceki_islem_hala_beklemede {
            get {
                return ResourceManager.GetString("onceki_islem_hala_beklemede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample recipe created. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ornek_recete_olusturuldu {
            get {
                return ResourceManager.GetString("ornek_recete_olusturuldu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto/Manual   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string otomanual {
            get {
                return ResourceManager.GetString("otomanual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter cannot be changed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string parametre_degistirilemiyor {
            get {
                return ResourceManager.GetString("parametre_degistirilemiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDU negotiation failed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string pdu_protokol_veri_birimi_muzakeresi_basarisiz_oldu {
            get {
                return ResourceManager.GetString("pdu_protokol_veri_birimi_muzakeresi_basarisiz_oldu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot start PLC. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string plc_baslatilamiyor {
            get {
                return ResourceManager.GetString("plc_baslatilamiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot stop PLC. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string plc_durdurulamiyor {
            get {
                return ResourceManager.GetString("plc_durdurulamiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLC already running. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string plc_zaten_calisiyor {
            get {
                return ResourceManager.GetString("plc_zaten_calisiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLC already stopped. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string plc_zaten_durdurulmus {
            get {
                return ResourceManager.GetString("plc_zaten_durdurulmus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid response from PLC. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string plcden_alinan_yanit_gecersiz {
            get {
                return ResourceManager.GetString("plcden_alinan_yanit_gecersiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PlcLaminationIP benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string plclaminationip {
            get {
                return ResourceManager.GetString("plclaminationip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting to PLCs... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string plclere_baglaniliyor {
            get {
                return ResourceManager.GetString("plclere_baglaniliyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Errors Occurred During Startup   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string program_acilirken_bazi_hatalar_olustu {
            get {
                return ResourceManager.GetString("program_acilirken_bazi_hatalar_olustu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copying from RAM to ROM failed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ramden_roma_kopyalama_basarisiz_oldu {
            get {
                return ResourceManager.GetString("ramden_roma_kopyalama_basarisiz_oldu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe Name   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string recete_adi {
            get {
                return ResourceManager.GetString("recete_adi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe saved successfully. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string recete_basariyla_kaydedildi {
            get {
                return ResourceManager.GetString("recete_basariyla_kaydedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe deleted successfully. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string recete_basariyla_silindi {
            get {
                return ResourceManager.GetString("recete_basariyla_silindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe not found. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string recete_bulunamadi {
            get {
                return ResourceManager.GetString("recete_bulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Recipe   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string recete_duzenle {
            get {
                return ResourceManager.GetString("recete_duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Recipe clicked benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string recete_ekle_tiklandi {
            get {
                return ResourceManager.GetString("recete_ekle_tiklandi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error checking recipe folder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string recete_klasörü_kontrolünde_hata {
            get {
                return ResourceManager.GetString("recete_klasörü_kontrolünde_hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while reading the recipe benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string recete_okunurken_hata_olustu {
            get {
                return ResourceManager.GetString("recete_okunurken_hata_olustu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe Creation Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string recete_olusturma_hatasi {
            get {
                return ResourceManager.GetString("recete_olusturma_hatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Recipe benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string recete_sec {
            get {
                return ResourceManager.GetString("recete_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A recipe must contain at least one step. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string recetede_en_az_1_adim_olmalı {
            get {
                return ResourceManager.GetString("recetede_en_az_1_adim_olmalı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe G1 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string receteDegeri {
            get {
                return ResourceManager.GetString("receteDegeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe G2 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string receteDegeri2 {
            get {
                return ResourceManager.GetString("receteDegeri2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipes   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string receteler {
            get {
                return ResourceManager.GetString("receteler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipes folder created. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string receteler_klasoru_olusturuldu {
            get {
                return ResourceManager.GetString("receteler_klasoru_olusturuldu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipes checked. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string receteler_kontrol_edildi {
            get {
                return ResourceManager.GetString("receteler_kontrol_edildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking recipes... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string receteler_kontrol_ediliyor {
            get {
                return ResourceManager.GetString("receteler_kontrol_ediliyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string recipe {
            get {
                return ResourceManager.GetString("recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string recipes {
            get {
                return ResourceManager.GetString("recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample Recipe benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sample_recipe {
            get {
                return ResourceManager.GetString("sample_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SER-MAK Makine benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sermak_makina {
            get {
                return ResourceManager.GetString("sermak_makina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string servis {
            get {
                return ResourceManager.GetString("servis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sifre_gerekli {
            get {
                return ResourceManager.GetString("sifre_gerekli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compression operation failed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sikistirma_islemi_basarisiz_oldu {
            get {
                return ResourceManager.GetString("sikistirma_islemi_basarisiz_oldu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duration (min)  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sure {
            get {
                return ResourceManager.GetString("sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tamam {
            get {
                return ResourceManager.GetString("tamam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buffer size is too small. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tampon_boyutu_cok_kucuk {
            get {
                return ResourceManager.GetString("tampon_boyutu_cok_kucuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TCP host unreachable. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tcp_ana_bilgisayar_erisilemez {
            get {
                return ResourceManager.GetString("tcp_ana_bilgisayar_erisilemez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TCP connection failed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tcp_baglantisi_basarisiz_oldu {
            get {
                return ResourceManager.GetString("tcp_baglantisi_basarisiz_oldu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TCP not connected. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tcp_baglantisi_kurulmamis {
            get {
                return ResourceManager.GetString("tcp_baglantisi_kurulmamis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TCP connection reset. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tcp_baglantisi_sifirlandi {
            get {
                return ResourceManager.GetString("tcp_baglantisi_sifirlandi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TCP connection timed out. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tcp_baglantisi_zaman_asimina_ugradi {
            get {
                return ResourceManager.GetString("tcp_baglantisi_zaman_asimina_ugradi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TCP socket creation failed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tcp_soketi_olusturulamadi {
            get {
                return ResourceManager.GetString("tcp_soketi_olusturulamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to receive data over TCP. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tcp_uzerinden_veri_alinamadi {
            get {
                return ResourceManager.GetString("tcp_uzerinden_veri_alinamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to send data over TCP. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tcp_uzerinden_veri_gonderilemedi {
            get {
                return ResourceManager.GetString("tcp_uzerinden_veri_gonderilemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TCP data receive timed out. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tcp_veri_alimi_zaman_asimina_ugradi {
            get {
                return ResourceManager.GetString("tcp_veri_alimi_zaman_asimina_ugradi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TCP data send timed out. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tcp_veri_gonderimi_zaman_asimina_ugradi {
            get {
                return ResourceManager.GetString("tcp_veri_gonderimi_zaman_asimina_ugradi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Alarms benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Temizle {
            get {
                return ResourceManager.GetString("Temizle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TimerAction benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string timeraction {
            get {
                return ResourceManager.GetString("timeraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Duration :  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string toplam_süre {
            get {
                return ResourceManager.GetString("toplam_süre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data size exceeds PDU limit. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string veri_boyutu_pdu_sinirini_asiyor {
            get {
                return ResourceManager.GetString("veri_boyutu_pdu_sinirini_asiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string x {
            get {
                return ResourceManager.GetString("x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only partial data was read. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yalnizca_kismi_veri_okundu {
            get {
                return ResourceManager.GetString("yalnizca_kismi_veri_okundu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only partial data was written. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yalnizca_kismi_veri_yazildi {
            get {
                return ResourceManager.GetString("yalnizca_kismi_veri_yazildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Written data size mismatch. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yazilan_veri_boyutu_uyumsuz {
            get {
                return ResourceManager.GetString("yazilan_veri_boyutu_uyumsuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Step benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yeniAdim {
            get {
                return ResourceManager.GetString("yeniAdim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load sequence failed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yukleme_sirasi_basarisiz_oldu {
            get {
                return ResourceManager.GetString("yukleme_sirasi_basarisiz_oldu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading...   benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yukleniyor {
            get {
                return ResourceManager.GetString("yukleniyor", resourceCulture);
            }
        }
    }
}
